#!/bin/bash

# 实验：测试 claude --resume 的行为

TRANSCRIPT_PATH="$HOME/.claude/projects/-Users-higuaifan-Desktop-hi-----claude-test"

echo "=== 实验 1: 原生 --resume 行为 ==="
echo ""
echo "步骤："
echo "1. 创建新 session，发送消息 'test1'"
echo "2. 退出"
echo "3. --resume 同一个 session，发送消息 'test2'"
echo "4. 退出"
echo "5. --resume 同一个 session，发送消息 'test3'"
echo "6. 查看 transcript，分析 parentUuid 链"
echo ""
echo "请手动执行以下步骤："
echo ""
echo "# 第一次运行（新 session）"
echo "cd /Users/higuaifan/Desktop/hi/小工具/claude/test"
echo "claude"
echo "> test1"
echo "> /exit"
echo ""
echo "# 记录 session ID（从输出中获取）"
echo "SESSION_ID=<从上面获取的 session id>"
echo ""
echo "# 第二次运行（resume）"
echo "claude --resume \$SESSION_ID"
echo "> test2"
echo "> /exit"
echo ""
echo "# 第三次运行（resume）"
echo "claude --resume \$SESSION_ID"
echo "> test3"
echo "> /exit"
echo ""
echo "# 分析 transcript"
echo "cat ~/.claude/projects/-Users-higuaifan-Desktop-hi-----claude-test/\$SESSION_ID.jsonl | jq -r '{type: .type, uuid: .uuid, parentUuid: .parentUuid, content: (.message.content[0].text // .message.content[0].type // \"system\")}'"
