// Session Reader FFI - C Header
//
// 为 VlaudeKit (Swift) 提供 Claude 会话文件读取能力。
// 自动生成，请勿手动编辑。
//
// 使用说明：
// 1. 所有返回的字符串必须通过 sr_free_string() 释放
// 2. Reader 实例必须通过 sr_destroy() 释放
// 3. 返回 NULL 表示操作失败


#ifndef SESSION_READER_FFI_H
#define SESSION_READER_FFI_H

/* Warning: this file is auto-generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Session Reader 句柄
 */
typedef struct SRReader SRReader;

/**
 * 创建 Reader 实例
 *
 * # 返回
 * - 成功：返回 Reader 指针
 * - 失败：返回 null
 *
 * # Safety
 * 调用者负责通过 `sr_destroy` 释放返回的指针
 */
struct SRReader *sr_create(void);

/**
 * 使用自定义路径创建 Reader 实例
 *
 * # 参数
 * - `projects_path`: Claude projects 目录路径（如 ~/.claude/projects）
 *
 * # Safety
 * - `projects_path` 必须是有效的 UTF-8 C 字符串
 * - 调用者负责通过 `sr_destroy` 释放返回的指针
 */
struct SRReader *sr_create_with_path(const char *projects_path);

/**
 * 释放 Reader 实例
 *
 * # Safety
 * - `reader` 必须是 `sr_create` 或 `sr_create_with_path` 返回的有效指针
 * - 只能调用一次
 */
void sr_destroy(struct SRReader *reader);

/**
 * 列出所有项目
 *
 * # 参数
 * - `reader`: Reader 指针
 * - `limit`: 最大返回数量，0 表示不限制
 *
 * # 返回
 * - 成功：返回 JSON 字符串（ProjectInfo 数组）
 * - 失败：返回 null
 *
 * # Safety
 * - `reader` 必须是有效指针
 * - 调用者负责通过 `sr_free_string` 释放返回的字符串
 */
char *sr_list_projects(struct SRReader *reader, uint32_t limit);

/**
 * 列出项目下的所有会话
 *
 * # 参数
 * - `reader`: Reader 指针
 * - `project_path`: 项目路径（可选，null 表示列出所有项目的会话）
 *
 * # 返回
 * - 成功：返回 JSON 字符串（SessionMeta 数组）
 * - 失败：返回 null
 *
 * # Safety
 * - `reader` 必须是有效指针
 * - `project_path` 如果非 null，必须是有效的 UTF-8 C 字符串
 * - 调用者负责通过 `sr_free_string` 释放返回的字符串
 */
char *sr_list_sessions(struct SRReader *reader, const char *project_path);

/**
 * 查找最新会话
 *
 * # 参数
 * - `reader`: Reader 指针
 * - `project_path`: 项目路径
 * - `within_seconds`: 时间范围（秒），0 表示不限制
 *
 * # 返回
 * - 成功：返回 JSON 字符串（SessionMeta 或 null）
 * - 失败：返回 null
 *
 * # Safety
 * - `reader` 必须是有效指针
 * - `project_path` 必须是有效的 UTF-8 C 字符串
 * - 调用者负责通过 `sr_free_string` 释放返回的字符串
 */
char *sr_find_latest_session(struct SRReader *reader,
                             const char *project_path,
                             uint64_t within_seconds);

/**
 * 读取会话消息
 *
 * # 参数
 * - `reader`: Reader 指针
 * - `session_path`: 会话文件完整路径
 * - `limit`: 最大返回数量
 * - `offset`: 偏移量
 * - `order_asc`: true=升序, false=降序
 *
 * # 返回
 * - 成功：返回 JSON 字符串（MessagesResult）
 * - 失败：返回 null
 *
 * # Safety
 * - `reader` 必须是有效指针
 * - `session_path` 必须是有效的 UTF-8 C 字符串
 * - 调用者负责通过 `sr_free_string` 释放返回的字符串
 */
char *sr_read_messages(struct SRReader *reader,
                       const char *session_path,
                       uint32_t limit,
                       uint32_t offset,
                       bool order_asc);

/**
 * 编码项目路径为 Claude 目录名
 *
 * # 参数
 * - `path`: 项目路径（如 /Users/xxx/project）
 *
 * # 返回
 * - 返回编码后的目录名（如 -Users-xxx-project）
 *
 * # Safety
 * - `path` 必须是有效的 UTF-8 C 字符串
 * - 调用者负责通过 `sr_free_string` 释放返回的字符串
 */
char *sr_encode_path(const char *path);

/**
 * 解码 Claude 目录名为项目路径
 *
 * # 参数
 * - `encoded`: 编码后的目录名（如 -Users-xxx-project）
 *
 * # 返回
 * - 返回解码后的路径（如 /Users/xxx/project）
 *
 * # Safety
 * - `encoded` 必须是有效的 UTF-8 C 字符串
 * - 调用者负责通过 `sr_free_string` 释放返回的字符串
 */
char *sr_decode_path(const char *encoded);

/**
 * 解析 JSONL 会话文件，用于索引到 SharedDb
 *
 * 会正确读取 cwd 来确定真实的项目路径，避免中文路径解析错误
 *
 * # 参数
 * - `reader`: Reader 指针
 * - `jsonl_path`: JSONL 文件完整路径
 *
 * # 返回
 * - 成功：返回 JSON 字符串（IndexableSession）
 * - 文件为空或无有效消息：返回 "null"
 * - 失败：返回 null
 *
 * # Safety
 * - `reader` 必须是有效指针
 * - `jsonl_path` 必须是有效的 UTF-8 C 字符串
 * - 调用者负责通过 `sr_free_string` 释放返回的字符串
 */
char *sr_parse_session_for_index(struct SRReader *reader, const char *jsonl_path);

/**
 * 释放由本库返回的字符串
 *
 * # Safety
 * - `s` 必须是本库函数返回的字符串指针
 * - 只能调用一次
 */
void sr_free_string(char *s);

/**
 * 获取库版本号
 *
 * # 返回
 * - 返回静态版本字符串，不需要释放
 */
const char *sr_version(void);

#endif /* SESSION_READER_FFI_H */
