#ifndef VLAUDE_FFI_H
#define VLAUDE_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI 安全的 Daemon 句柄
 */
typedef struct VlaudeDaemon VlaudeDaemon;

/**
 * 检查加载状态回调 FFI 类型
 * 参数: (session_id, request_id)
 * 返回: bool (is_loading)
 */
typedef bool (*CheckLoadingCallbackFn)(const char*, const char*);

/**
 * 创建会话结果 (FFI)
 */
typedef struct CreateSessionResultFFI {
  bool success;
  char *session_id;
  char *project_path;
  char *encoded_dir_name;
  char *error;
} CreateSessionResultFFI;

/**
 * 创建会话回调 FFI 类型
 * 参数: (project_path, prompt, request_id)
 * 返回: CreateSessionResultFFI
 */
typedef struct CreateSessionResultFFI (*CreateSessionCallbackFn)(const char*,
                                                                 const char*,
                                                                 const char*);

/**
 * FFI 回调类型
 */
typedef void (*MobileViewingCallbackFn)(const char*, bool);

/**
 * 发送消息结果 (FFI)
 */
typedef struct SendMessageResultFFI {
  bool success;
  char *error;
  char *message_id;
} SendMessageResultFFI;

/**
 * 发送消息回调 FFI 类型
 * 参数: (session_id, text, request_id)
 * 返回: SendMessageResultFFI
 */
typedef struct SendMessageResultFFI (*SendMessageCallbackFn)(const char*, const char*, const char*);

/**
 * 连接到服务器并启动事件循环
 *
 * # Safety
 * `daemon` 必须是 `vlaude_create` 返回的有效指针
 */
bool vlaude_connect(struct VlaudeDaemon *daemon);

/**
 * 创建 Daemon 实例
 *
 * # Safety
 * 调用者负责通过 `vlaude_destroy` 释放返回的指针
 */
struct VlaudeDaemon *vlaude_create(const char *server_url, const char *hostname);

/**
 * 释放 Daemon 实例
 *
 * # Safety
 * `daemon` 必须是 `vlaude_create` 返回的有效指针，且只能调用一次
 */
void vlaude_destroy(struct VlaudeDaemon *daemon);

/**
 * 断开连接
 *
 * # Safety
 * `daemon` 必须是 `vlaude_create` 返回的有效指针
 */
void vlaude_disconnect(struct VlaudeDaemon *daemon);

/**
 * 释放 FFI 返回的字符串
 *
 * # Safety
 * `ptr` 必须是本模块 FFI 函数返回的有效指针，且只能调用一次
 */
void vlaude_free_string(char *ptr);

/**
 * 获取会话消息
 *
 * # Arguments
 * * `session_id` - 会话 ID（C 字符串）
 * * `limit` - 返回消息数量限制
 * * `offset` - 偏移量（分页）
 *
 * 返回 JSON 字符串，格式：
 * ```json
 * {
 *   "messages": [
 *     {
 *       "id": 1,
 *       "uuid": "msg-uuid",
 *       "type": "user",
 *       "content_text": "Hello",
 *       "timestamp": 1704067200000
 *     }
 *   ]
 * }
 * ```
 *
 * # Safety
 * - `session_id` 必须是有效的 UTF-8 C 字符串
 * - 返回的字符串必须通过 `vlaude_free_string` 释放
 */
char *vlaude_get_messages(const char *session_id, uint32_t limit, uint32_t offset);

/**
 * 按 Turn 数量获取会话消息（Turn-based 分页）
 *
 * # Arguments
 * * `session_id` - 会话 ID（C 字符串）
 * * `turns_limit` - 返回最近 N 个 Turn
 * * `before` - 翻页游标，-1 表示首页
 *
 * 返回 JSON: `{ "messages": [...], "total": N, "hasMore": bool, "openTurn": bool, "nextCursor": N|null }`
 *
 * # Safety
 * - `session_id` 必须是有效的 UTF-8 C 字符串
 * - 返回的字符串必须通过 `vlaude_free_string` 释放
 */
char *vlaude_get_messages_by_turns(const char *session_id,
                                   uint32_t turns_limit,
                                   int64_t before,
                                   const char *detail);

/**
 * 获取数据库统计信息
 *
 * 返回 JSON 字符串，格式：
 * ```json
 * {
 *   "project_count": 10,
 *   "session_count": 100,
 *   "message_count": 5000
 * }
 * ```
 *
 * # Safety
 * 返回的字符串必须通过 `vlaude_free_string` 释放
 */
char *vlaude_get_stats(void);

/**
 * 列出所有项目（带统计信息）
 *
 * 返回 JSON 字符串，格式：
 * ```json
 * {
 *   "projects": [
 *     {
 *       "id": 1,
 *       "name": "project-name",
 *       "path": "/path/to/project",
 *       "session_count": 10,
 *       "message_count": 100,
 *       "last_activity_at": "2024-01-01T00:00:00Z"
 *     }
 *   ]
 * }
 * ```
 *
 * # Safety
 * 返回的字符串必须通过 `vlaude_free_string` 释放
 */
char *vlaude_list_projects(uint32_t limit, uint32_t offset);

/**
 * 列出指定项目的会话
 *
 * # Arguments
 * * `project_path` - 项目路径（C 字符串）
 *
 * 返回 JSON 字符串，格式：
 * ```json
 * {
 *   "sessions": [
 *     {
 *       "session_id": "abc123",
 *       "project_id": 1,
 *       "project_path": "/path/to/project",
 *       "project_name": "project-name",
 *       "message_count": 50,
 *       "created_at": "2024-01-01T00:00:00Z",
 *       "updated_at": "2024-01-02T00:00:00Z"
 *     }
 *   ]
 * }
 * ```
 *
 * # Safety
 * - `project_path` 必须是有效的 UTF-8 C 字符串
 * - 返回的字符串必须通过 `vlaude_free_string` 释放
 */
char *vlaude_list_sessions(const char *project_path, uint32_t limit, uint32_t offset);

/**
 * 全文搜索
 *
 * # Arguments
 * * `query` - 搜索关键词（C 字符串）
 * * `limit` - 返回结果数量限制
 *
 * 返回 JSON 字符串，格式：
 * ```json
 * {
 *   "results": [
 *     {
 *       "message_id": 1,
 *       "session_id": "abc123",
 *       "project_path": "/path/to/project",
 *       "content_text": "matched content...",
 *       "snippet": "...highlighted snippet...",
 *       "rank": 0.95
 *     }
 *   ]
 * }
 * ```
 *
 * # Safety
 * - `query` 必须是有效的 UTF-8 C 字符串
 * - 返回的字符串必须通过 `vlaude_free_string` 释放
 */
char *vlaude_search(const char *query, uint32_t limit);

/**
 * 设置检查加载状态回调 (ETerm)
 *
 * # Safety
 * `daemon` 必须是有效指针
 */
void vlaude_set_check_loading_callback(struct VlaudeDaemon *daemon,
                                       CheckLoadingCallbackFn callback);

/**
 * 设置创建会话回调 (ETerm)
 *
 * # Safety
 * `daemon` 必须是有效指针
 */
void vlaude_set_create_session_callback(struct VlaudeDaemon *daemon,
                                        CreateSessionCallbackFn callback);

/**
 * 设置 Mobile 查看状态回调
 *
 * # Safety
 * `daemon` 必须是有效指针
 */
void vlaude_set_mobile_viewing_callback(struct VlaudeDaemon *daemon,
                                        MobileViewingCallbackFn callback);

/**
 * 设置发送消息回调 (ETerm)
 *
 * # Safety
 * `daemon` 必须是有效指针
 */
void vlaude_set_send_message_callback(struct VlaudeDaemon *daemon, SendMessageCallbackFn callback);

/**
 * 获取版本号
 *
 * # Safety
 * 返回的字符串是静态的，不需要释放
 */
const char *vlaude_version(void);

#endif /* VLAUDE_FFI_H */
