#ifndef SOCKET_CLIENT_FFI_H
#define SOCKET_CLIENT_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI 错误码
 */
typedef enum SocketClientError {
  SUCCESS = 0,
  NULL_POINTER = 1,
  INVALID_UTF8 = 2,
  CONNECTION_FAILED = 3,
  NOT_CONNECTED = 4,
  EMIT_FAILED = 5,
  RUNTIME_ERROR = 6,
  REGISTRY_ERROR = 7,
  UNKNOWN = 99,
} SocketClientError;

/**
 * 不透明句柄
 */
typedef struct SocketClientHandle SocketClientHandle;

/**
 * 事件回调类型
 */
typedef void (*EventCallbackFn)(const char *event, const char *data, void *user_data);

/**
 * 连接到服务器
 *
 * # Safety
 * - `handle` 必须是有效句柄
 */
enum SocketClientError socket_client_connect(struct SocketClientHandle *handle);

/**
 * 使用 Redis 服务发现连接
 *
 * 1. 初始化 Redis 连接
 * 2. 从 Redis 发现 Server 地址
 * 3. 连接 Socket
 * 4. 注册到 Redis
 * 5. 启动心跳
 *
 * # Safety
 * - `handle` 必须是有效句柄
 */
enum SocketClientError socket_client_connect_with_discovery(struct SocketClientHandle *handle);

/**
 * 创建 Socket 客户端
 *
 * # Safety
 * - `url` 必须是有效的 UTF-8 C 字符串（如 "https://localhost:10005"）
 * - `namespace` 必须是有效的 UTF-8 C 字符串（如 "/daemon"），可为 null 使用默认值
 * - 返回的句柄需要通过 `socket_client_destroy` 释放
 */
enum SocketClientError socket_client_create(const char *url,
                                            const char *namespace_,
                                            struct SocketClientHandle **out_handle);

/**
 * 创建带 Redis 配置的 Socket 客户端
 *
 * # Safety
 * - `url` 必须是有效的 UTF-8 C 字符串
 * - `namespace` 可为 null
 * - `redis_host` 可为 null（不启用 Redis）
 * - `device_id`, `device_name`, `platform`, `version` 启用 Redis 时必填
 * - 返回的句柄需要通过 `socket_client_destroy` 释放
 */
enum SocketClientError socket_client_create_with_redis(const char *url,
                                                       const char *namespace_,
                                                       const char *redis_host,
                                                       uint16_t redis_port,
                                                       const char *redis_password,
                                                       const char *device_id,
                                                       const char *device_name,
                                                       const char *platform,
                                                       const char *version,
                                                       uint64_t ttl,
                                                       struct SocketClientHandle **out_handle);

/**
 * 销毁 Socket 客户端
 *
 * # Safety
 * - `handle` 必须是 `socket_client_create` 返回的有效句柄
 * - 调用后句柄不再有效
 */
void socket_client_destroy(struct SocketClientHandle *handle);

/**
 * 断开连接
 *
 * # Safety
 * - `handle` 必须是有效句柄
 */
void socket_client_disconnect(struct SocketClientHandle *handle);

/**
 * 发现 Server 地址
 *
 * 返回发现的第一个 Server 地址，如果没有则返回 null
 * 调用者需要使用 `socket_client_free_string` 释放返回的字符串
 *
 * # Safety
 * - `handle` 必须是有效句柄
 */
char *socket_client_discover_server(struct SocketClientHandle *handle);

/**
 * 发送事件
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `event` 和 `json_data` 必须是有效的 UTF-8 C 字符串
 */
enum SocketClientError socket_client_emit(struct SocketClientHandle *handle,
                                          const char *event,
                                          const char *json_data);

/**
 * 释放 C 字符串
 *
 * # Safety
 * - `s` 必须是由本库创建的 C 字符串
 */
void socket_client_free_string(char *s);

/**
 * 检查是否已连接
 *
 * # Safety
 * - `handle` 必须是有效句柄
 */
bool socket_client_is_connected(const struct SocketClientHandle *handle);

/**
 * 上报新消息
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `session_id` 和 `message_json` 必须是有效字符串
 */
enum SocketClientError socket_client_notify_new_message(struct SocketClientHandle *handle,
                                                        const char *session_id,
                                                        const char *message_json);

/**
 * 上报项目更新
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `project_path` 必须是有效字符串
 * - `metadata_json` 可为 null
 */
enum SocketClientError socket_client_notify_project_update(struct SocketClientHandle *handle,
                                                           const char *project_path,
                                                           const char *metadata_json);

/**
 * 注册 daemon
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `hostname`, `platform`, `version` 必须是有效的 UTF-8 C 字符串
 */
enum SocketClientError socket_client_register(struct SocketClientHandle *handle,
                                              const char *hostname,
                                              const char *platform,
                                              const char *version);

/**
 * 上报离线状态
 *
 * # Safety
 * - `handle` 必须是有效句柄
 */
enum SocketClientError socket_client_report_offline(struct SocketClientHandle *handle);

/**
 * 上报在线状态
 *
 * # Safety
 * - `handle` 必须是有效句柄
 */
enum SocketClientError socket_client_report_online(struct SocketClientHandle *handle);

/**
 * 上报项目数据
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `projects_json` 必须是有效的 JSON 数组字符串
 * - `request_id` 可为 null
 */
enum SocketClientError socket_client_report_project_data(struct SocketClientHandle *handle,
                                                         const char *projects_json,
                                                         const char *request_id);

/**
 * 上报会话消息
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `session_id`, `project_path`, `messages_json` 必须是有效字符串
 * - `request_id` 可为 null
 */
enum SocketClientError socket_client_report_session_messages(struct SocketClientHandle *handle,
                                                             const char *session_id,
                                                             const char *project_path,
                                                             const char *messages_json,
                                                             uintptr_t total,
                                                             bool has_more,
                                                             const char *request_id);

/**
 * 上报会话元数据
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `sessions_json` 必须是有效的 JSON 数组字符串
 * - `project_path` 和 `request_id` 可为 null
 */
enum SocketClientError socket_client_report_session_metadata(struct SocketClientHandle *handle,
                                                             const char *sessions_json,
                                                             const char *project_path,
                                                             const char *request_id);

/**
 * 发送加载状态检查结果
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `request_id` 必须是有效字符串
 */
enum SocketClientError socket_client_send_check_loading_result(struct SocketClientHandle *handle,
                                                               const char *request_id,
                                                               bool loading);

/**
 * 发送消息发送结果
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `request_id` 必须是有效字符串
 * - `message` 和 `via` 可为 null
 */
enum SocketClientError socket_client_send_message_result(struct SocketClientHandle *handle,
                                                         const char *request_id,
                                                         bool success,
                                                         const char *message,
                                                         const char *via);

/**
 * 发送会话创建结果
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `request_id` 必须是有效字符串
 * - 其他字符串参数可为 null
 */
enum SocketClientError socket_client_send_session_created_result(struct SocketClientHandle *handle,
                                                                 const char *request_id,
                                                                 bool success,
                                                                 const char *session_id,
                                                                 const char *encoded_dir_name,
                                                                 const char *transcript_path,
                                                                 const char *error);

/**
 * 设置事件回调
 *
 * 当收到服务器下行事件时，会调用此回调
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `callback` 在整个句柄生命周期内必须有效
 * - `user_data` 可为 null
 */
void socket_client_set_event_callback(struct SocketClientHandle *handle,
                                      EventCallbackFn callback,
                                      void *user_data);

/**
 * 更新 Redis 中的 Session 列表
 *
 * # Safety
 * - `handle` 必须是有效句柄
 * - `sessions_json` 必须是有效的 JSON 数组字符串，格式：
 *   `[{"sessionId": "xxx", "projectPath": "/path"}]`
 */
enum SocketClientError socket_client_update_sessions(struct SocketClientHandle *handle,
                                                     const char *sessions_json);

/**
 * 获取版本号
 *
 * # Safety
 * 返回静态字符串，无需释放
 */
const char *socket_client_version(void);

#endif  /* SOCKET_CLIENT_FFI_H */
